### ISSUE TITLE
填写激活码了仍然提示已过期

### ISSUE THREAD

**Issue by mozhux** [MarkMindCkm/siyuan-markmind#10]
如题，已经购买填写了激活码，但是插件仍提示已过期
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/46953371/30125e81-f9b2-495a-a14b-e9da9ba852a7)
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/46953371/494a23b5-2248-43dd-8004-a90b447704f3)
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/46953371/e43cf169-20d5-40b5-bfe7-a6130bbb7598)

**Comment by MarkMindCkm** [comment]
似乎买错了, 买了 obsidian markmind 激活码，需要购买 siyuan  markmind 激活码 ，你把 邮箱发给我，我发给你一个吧

**Comment by mozhux** [comment]
也很奇怪。。我买的时候也是直接点的siyuan那个页面去购买的，看到ob的还很疑惑，还以为是还没专门弄思源的名称。。
wutingkun2012@hotmail.com

**Comment by MarkMindCkm** [comment]
> 也很奇怪。。我买的时候也是直接点的siyuan那个页面去购买的，看到ob的还很疑惑，还以为是还没专门弄思源的名称。。 [wutingkun2012@hotmail.com](mailto:wutingkun2012@hotmail.com)

已发送，试一下

**Comment by mozhux** [comment]
> > 也很奇怪。。我买的时候也是直接点的siyuan那个页面去购买的，看到ob的还很疑惑，还以为是还没专门弄思源的名称。。 [wutingkun2012@hotmail.com](mailto:wutingkun2012@hotmail.com)
> 
> 已发送，试一下

激活成功了，ob的删了吧
