### ISSUE TITLE
0.08 支持悬浮

### ISSUE THREAD

**Issue by SamJ2018** [MarkMindCkm/siyuan-markmind#11]
请问不是支持块链接悬浮显示吗，为什么鼠标放上去没有反应？
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/37620490/af12c418-eb2d-46f9-82c6-bb0bee7b0edb)

**Comment by MarkMindCkm** [comment]
目前支持是在节点内部，这个链接下个版本更新支持

**Comment by SamJ2018** [comment]
请问是什么节点内部？因为没有更新日志和演示，从字面上不是很理解，希望后面有新特性能加上演示。

**Comment by MarkMindCkm** [comment]
好的，就是编辑节点，直接将链接粘贴进去，或者是 `[a 链接](siyuan://blocks/dawqeqe-sw2)` 这种形式
