### ISSUE TITLE
Mac已经安装最新dev1，新建导图不成功

### ISSUE THREAD

**Issue by terwer** [MarkMindCkm/siyuan-markmind#2]
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/3259282/1a93b8cc-5916-46e2-908a-560585795dbc)

如图，新建之后去设置的目录，文件并没有新建。没有错误提示

![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/3259282/a536ac63-0a5e-487e-8173-a25dcb3697a2)

puFile返回是0。但是文件没有新建

**Comment by terwer** [comment]
发现了问题所在。
设置了自定义目录之后，他还是找 /data/markmind默认目录。改成默认目录文件才读出来。
也就是说，自定义目录无效。

**Comment by MarkMindCkm** [comment]
> 发现了问题所在。 设置了自定义目录之后，他还是找 /data/markmind默认目录。改成默认目录文件才读出来。 也就是说，自定义目录无效。

设置  自定义目录 得在菜单里执行一下 初始化插件，因为得创建文件夹

**Comment by MarkMindCkm** [comment]
https://github.com/MarkMindCkm/siyuan-markmind/releases/tag/0.0.5
