### ISSUE TITLE
提示Markmind:试用期或激活码已过期

### ISSUE THREAD

**Issue by DemoRain** [MarkMindCkm/siyuan-markmind#25]
已经购买独立版 markmind 软件永久激活，输入激活码后还是提示激活码过期

**Comment by DemoRain** [comment]
是我买错了吗，我用的是 siyuan 的

**Comment by MarkMindCkm** [comment]
> 是我买错了吗，我用的是 siyuan 的

把你的邮箱发给我，我给生成一个思源激活码，然后发到你的邮箱

**Comment by DemoRain** [comment]
这个也是买断的吗？后续有没有在 siyuan 上的开发计划了，短期没有的话麻烦退下款，或者我买 1 个月试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarkMindCkm/siyuan-markmind"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月25日(星期二) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarkMindCkm/siyuan-markmind] 提示Markmind:试用期或激活码已过期 (Issue #25)





  
是我买错了吗，我用的是 siyuan 的
  
把你的邮箱发给我，我给生成一个思源激活码，然后发到你的邮箱

**Comment by MarkMindCkm** [comment]
> 这个也是买断的吗？后续有没有在 siyuan 上的开发计划了，短期没有的话麻烦退下款，或者我买 1 个月试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MarkMindCkm/siyuan-markmind" ***@***.***&gt;; 发送时间:&nbsp;2024年6月25日(星期二) 中午11:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MarkMindCkm/siyuan-markmind] 提示Markmind:试用期或激活码已过期 (Issue #25) 是我买错了吗，我用的是 siyuan 的 把你的邮箱发给我，我给生成一个思源激活码，然后发到你的邮箱 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

已经发送给你了
