### ISSUE TITLE
子节点分离后再重新连接后层级错位

### ISSUE THREAD

**Issue by 5kyfkr** [MarkMindCkm/siyuan-markmind#3]
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/63196026/7814cc81-b101-4ae7-a0b5-c4f354e46b20)
如图，先将二极三级节点从一级节点分离，再将二极节点合并入一级节点，就会出现二极节点和三级节点位置倒转错位

**Comment by MarkMindCkm** [comment]
这是因为节点上存储了布局信息，你可以用菜单最后一个删除布局即可

**Comment by MarkMindCkm** [comment]
![微信图片_20230526074336](https://github.com/MarkMindCkm/siyuan-markmind/assets/18719494/d1f8b483-82e3-4b61-9b76-7ceb1c52a4c7)
