### ISSUE TITLE
FR：新建导图输入完名字之后，可以直接按回车或ctrl回车确认

### ISSUE THREAD

**Issue by deerainw** [MarkMindCkm/siyuan-markmind#4]
RT，目前打完字之后手要离开主键区用鼠标去点击保存，不太方便

<img width="516" alt="image" src="https://github.com/MarkMindCkm/siyuan-markmind/assets/32661922/456c7d44-10b2-4c7f-9b44-144f47459dfd">

**Comment by MarkMindCkm** [comment]
https://github.com/MarkMindCkm/siyuan-markmind/releases/tag/0.0.6
