### ISSUE TITLE
Not working SiYuan 2.8.9 on Linux

### ISSUE THREAD

**Issue by taozina0587** [MarkMindCkm/siyuan-markmind#6]
Buddy, plugin looks fantastic. But it's not working here on Linux. I activate the plugin in MarketPlace...
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/90691302/7da810b1-1b79-4eb7-b1e2-c925c0e15357)

Icon appeared in the menu
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/90691302/9e899de5-c8b1-40db-910f-f805ca0a12d5)

I try to create a map
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/90691302/b7af7d15-d534-4dae-8179-d8058e3c8869)

But nothing appears here!
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/90691302/1bcb00a6-987b-40c8-9eb2-03b6d3dcce7a)

I have already tried to refresh the folder and the maps using these buttons. Nothing appears...
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/90691302/40ec0b23-7ff1-43b4-b782-85fd2adea283)

**Comment by MarkMindCkm** [comment]
please click `init plugin` first in menu  , this commad can create a `markmind` folder in your `data` folder

**Comment by taozina0587** [comment]
I have done. Nothing happens...

**Comment by MarkMindCkm** [comment]
the api have some error , you can wait next version of siyuan

**Comment by MarkMindCkm** [comment]
https://github.com/MarkMindCkm/siyuan-markmind/releases/tag/0.0.7
