### ISSUE TITLE
插入的链接无法删除，输入框内的字符只能修改，无法清空

### ISSUE THREAD

**Issue by guopengfei1602** [MarkMindCkm/siyuan-markmind#7]
随便一个内容：
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/57949895/29f8a72d-2a45-4b20-ad4c-3aa3a866702e)

清空后，点击“√”

![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/57949895/772e0b03-a362-4d71-96dc-205e8564da9e)

没有变化：
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/57949895/5672ddbb-8e65-4b51-bcd8-0664a648f0fa)

似乎只能更改，不能清空。

****
额，还有几个稍微有点不舒服的地方：
1.  笔记是鼠标一放在图标上面就显示，但遇到上下主题都插入笔记时（有笔记的主题比较密集时），鼠标移动总会不小心碰到笔记，然后产生下面的情况：
![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/57949895/0125ddbe-d524-43cb-8bfa-e37eb5ef3b71)

![image](https://github.com/MarkMindCkm/siyuan-markmind/assets/57949895/0b5d9883-4455-4217-a423-a5ed3ade1e8e)

想让弹出的笔记消失还要点击空白处或笔记区域，但也会导致编辑框消失。对编辑过程稍微有些影响。
或许可以像Xmind一样点击笔记图标再显示笔记？

2. 思维导图的节点能否像思源的块一样，可以有自己的超链接或者被引用/被嵌入。

**Comment by MarkMindCkm** [comment]
这些功能后面改进，另外想要被引用或者被嵌入需要 api 支持
